// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function ConnectHost(arg1) {
  return window['go']['app']['App']['ConnectHost'](arg1);
}

export function DisconnectHost(arg1) {
  return window['go']['app']['App']['DisconnectHost'](arg1);
}

export function ListContainers(arg1) {
  return window['go']['app']['App']['ListContainers'](arg1);
}

export function ListHosts() {
  return window['go']['app']['App']['ListHosts']();
}

export function ListImages(arg1) {
  return window['go']['app']['App']['ListImages'](arg1);
}

export function ListNetworks(arg1) {
  return window['go']['app']['App']['ListNetworks'](arg1);
}

export function ListVolumes(arg1) {
  return window['go']['app']['App']['ListVolumes'](arg1);
}

export function RemoveHost(arg1) {
  return window['go']['app']['App']['RemoveHost'](arg1);
}

export function SetObserveMode(arg1, arg2) {
  return window['go']['app']['App']['SetObserveMode'](arg1, arg2);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
