// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {journal} from '../models';
import {domain} from '../models';

export function AddHost(arg1:app.AddHostInput):Promise<app.HostDTO>;

export function ApplyComposePlan(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function AuditTrail():Promise<journal.AuditStatus>;

export function BackupDatabase():Promise<string>;

export function CloseExecInput(arg1:string):Promise<void>;

export function ComposeDown(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function ComposeUp(arg1:string,arg2:string):Promise<void>;

export function ComputeComposePlan(arg1:string,arg2:string):Promise<domain.ComposePlan>;

export function ConnectHost(arg1:string):Promise<app.HostDTO>;

export function DisconnectHost(arg1:string):Promise<void>;

export function ExportJournal():Promise<string>;

export function GetPruneImpact(arg1:string):Promise<domain.PruneImpact>;

export function GetResourceHistory(arg1:string,arg2:string,arg3:number):Promise<Array<domain.ResourceSample>>;

export function HostExposure(arg1:string):Promise<domain.ExposureMap>;

export function KillContainer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ListContainers(arg1:string):Promise<Array<domain.Container>>;

export function ListHosts():Promise<Array<app.HostDTO>>;

export function ListImages(arg1:string):Promise<Array<domain.Image>>;

export function ListNetworks(arg1:string):Promise<Array<domain.Network>>;

export function ListStacks(arg1:string):Promise<Array<domain.Stack>>;

export function ListVolumes(arg1:string):Promise<Array<domain.Volume>>;

export function OperationHistory(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<Array<domain.Operation>>;

export function PruneBuildCache(arg1:string,arg2:boolean):Promise<number>;

export function PruneContainers(arg1:string,arg2:boolean):Promise<number>;

export function PruneImages(arg1:string,arg2:boolean,arg3:boolean):Promise<number>;

export function RemoveContainer(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function RemoveHost(arg1:string):Promise<void>;

export function RemoveVolume(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ResizeExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function SendExecInput(arg1:string,arg2:string):Promise<void>;

export function SetObserveMode(arg1:string,arg2:boolean):Promise<void>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StartExec(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainerLogs(arg1:string):Promise<void>;

export function StopContainerStats(arg1:string):Promise<void>;

export function StopExec(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:string):Promise<void>;

export function StreamContainerStats(arg1:string,arg2:string):Promise<void>;

export function SubscribeEvents(arg1:string):Promise<void>;

export function UnsubscribeEvents(arg1:string):Promise<void>;

export function Version():Promise<string>;
