// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';

export function ListContainers(arg1:string):Promise<Array<domain.Container>>;

export function ListImages(arg1:string):Promise<Array<domain.Image>>;

export function ListNetworks(arg1:string):Promise<Array<domain.Network>>;

export function ListVolumes(arg1:string):Promise<Array<domain.Volume>>;

export function LocalEngine():Promise<app.LocalEngineStatus>;

export function Version():Promise<string>;
