// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function AuditTrail() {
  return window['go']['app']['App']['AuditTrail']();
}

export function BackupDatabase() {
  return window['go']['app']['App']['BackupDatabase']();
}

export function ComposeDown(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComposeDown'](arg1, arg2, arg3, arg4);
}

export function ComposeUp(arg1, arg2) {
  return window['go']['app']['App']['ComposeUp'](arg1, arg2);
}

export function ConnectHost(arg1) {
  return window['go']['app']['App']['ConnectHost'](arg1);
}

export function DisconnectHost(arg1) {
  return window['go']['app']['App']['DisconnectHost'](arg1);
}

export function ExportJournal() {
  return window['go']['app']['App']['ExportJournal']();
}

export function GetPruneImpact(arg1) {
  return window['go']['app']['App']['GetPruneImpact'](arg1);
}

export function GetResourceHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetResourceHistory'](arg1, arg2, arg3);
}

export function KillContainer(arg1, arg2, arg3) {
  return window['go']['app']['App']['KillContainer'](arg1, arg2, arg3);
}

export function ListContainers(arg1) {
  return window['go']['app']['App']['ListContainers'](arg1);
}

export function ListHosts() {
  return window['go']['app']['App']['ListHosts']();
}

export function ListImages(arg1) {
  return window['go']['app']['App']['ListImages'](arg1);
}

export function ListNetworks(arg1) {
  return window['go']['app']['App']['ListNetworks'](arg1);
}

export function ListStacks(arg1) {
  return window['go']['app']['App']['ListStacks'](arg1);
}

export function ListVolumes(arg1) {
  return window['go']['app']['App']['ListVolumes'](arg1);
}

export function OperationHistory(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OperationHistory'](arg1, arg2, arg3, arg4);
}

export function PruneBuildCache(arg1, arg2) {
  return window['go']['app']['App']['PruneBuildCache'](arg1, arg2);
}

export function PruneContainers(arg1, arg2) {
  return window['go']['app']['App']['PruneContainers'](arg1, arg2);
}

export function PruneImages(arg1, arg2, arg3) {
  return window['go']['app']['App']['PruneImages'](arg1, arg2, arg3);
}

export function RemoveContainer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RemoveContainer'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveHost(arg1) {
  return window['go']['app']['App']['RemoveHost'](arg1);
}

export function RemoveVolume(arg1, arg2, arg3) {
  return window['go']['app']['App']['RemoveVolume'](arg1, arg2, arg3);
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function RestartContainer(arg1, arg2) {
  return window['go']['app']['App']['RestartContainer'](arg1, arg2);
}

export function SendExecInput(arg1, arg2) {
  return window['go']['app']['App']['SendExecInput'](arg1, arg2);
}

export function SetObserveMode(arg1, arg2) {
  return window['go']['app']['App']['SetObserveMode'](arg1, arg2);
}

export function StartContainer(arg1, arg2) {
  return window['go']['app']['App']['StartContainer'](arg1, arg2);
}

export function StartExec(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartExec'](arg1, arg2, arg3);
}

export function StopContainer(arg1, arg2) {
  return window['go']['app']['App']['StopContainer'](arg1, arg2);
}

export function StopContainerLogs(arg1) {
  return window['go']['app']['App']['StopContainerLogs'](arg1);
}

export function StopContainerStats(arg1) {
  return window['go']['app']['App']['StopContainerStats'](arg1);
}

export function StopExec(arg1) {
  return window['go']['app']['App']['StopExec'](arg1);
}

export function StreamContainerLogs(arg1, arg2) {
  return window['go']['app']['App']['StreamContainerLogs'](arg1, arg2);
}

export function StreamContainerStats(arg1, arg2) {
  return window['go']['app']['App']['StreamContainerStats'](arg1, arg2);
}

export function SubscribeEvents(arg1) {
  return window['go']['app']['App']['SubscribeEvents'](arg1);
}

export function UnsubscribeEvents(arg1) {
  return window['go']['app']['App']['UnsubscribeEvents'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
