// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListContainers(arg1) {
  return window['go']['app']['App']['ListContainers'](arg1);
}

export function ListImages(arg1) {
  return window['go']['app']['App']['ListImages'](arg1);
}

export function ListNetworks(arg1) {
  return window['go']['app']['App']['ListNetworks'](arg1);
}

export function ListVolumes(arg1) {
  return window['go']['app']['App']['ListVolumes'](arg1);
}

export function LocalEngine() {
  return window['go']['app']['App']['LocalEngine']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
