// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {domain} from '../models';

export function AddHost(arg1:app.AddHostInput):Promise<app.HostDTO>;

export function ConnectHost(arg1:string):Promise<app.HostDTO>;

export function DisconnectHost(arg1:string):Promise<void>;

export function GetPruneImpact(arg1:string):Promise<domain.PruneImpact>;

export function KillContainer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ListContainers(arg1:string):Promise<Array<domain.Container>>;

export function ListHosts():Promise<Array<app.HostDTO>>;

export function ListImages(arg1:string):Promise<Array<domain.Image>>;

export function ListNetworks(arg1:string):Promise<Array<domain.Network>>;

export function ListVolumes(arg1:string):Promise<Array<domain.Volume>>;

export function PruneBuildCache(arg1:string,arg2:boolean):Promise<number>;

export function PruneContainers(arg1:string,arg2:boolean):Promise<number>;

export function PruneImages(arg1:string,arg2:boolean,arg3:boolean):Promise<number>;

export function RemoveContainer(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function RemoveHost(arg1:string):Promise<void>;

export function RemoveVolume(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function SetObserveMode(arg1:string,arg2:boolean):Promise<void>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainerLogs(arg1:string):Promise<void>;

export function StopContainerStats(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:string):Promise<void>;

export function StreamContainerStats(arg1:string,arg2:string):Promise<void>;

export function Version():Promise<string>;
